core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *

app_name = 'rate'

urlpatterns = [
    path('', home, name='home'),
    path("rate-image/", rate_image, name='rate-image')
]

website/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

class RateStars(models.Model):
    image = models.ImageField(upload_to='images/')
    score = models.IntegerField(default=0, 
                               validators=[
                                   MaxValueValidator(5),
                                   MinValueValidator(0)
                               ]
                            )
    def __str__(self):
        return str(self.pk)

website/views.py
from django.http import JsonResponse
from django.shortcuts import render
from website.models import *

def home(request):
    rate = RateStars.objects.filter(score=3).order_by("?").first()
    context = {
        "rate":rate,
    }
    return render(request, 'home.html', context)

def rate_image(request):
    
	if request.method == "POST":
		el_id = request.POST.get("el_id")
		val = request.POST.get("val")
		rate = RateStars.objects.get(id=el_id)
		rate.score = val
		rate.save()
		return JsonResponse({"success": "true", "score": val}, safe=False)
	return JsonResponse({"success": "false"})

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Django Rate</title>
</head>
<body>

    <style>
        .checked{
            color: red;
        }
        .btns{
            border: none;
            background-color: transparent;
        }
    </style>
    
    {% if rate %}
    <div class="full">
        <h1>Bu home page</h1>
        <img src="{{ rate.image.url }}" alt="error" width="500" height="500">
        <a href="{% url 'rate:home' %}"><button>Next</button></a>
        <form class="rate-form" method="POST">
            {% csrf_token %}
            <button type="submit" class="fa fa-star fa-3x btns"></button>
            <button type="submit" class="fa fa-star fa-3x btns"></button>
            <button type="submit" class="fa fa-star fa-3x btns"></button>
            <button type="submit" class="fa fa-star fa-3x btns"></button>
            <button type="submit" class="fa fa-star fa-3x btns"></button>
        </form>
    </div>
    {% else %}
    <h1>Rate qilgani rasm qolmadi</h1>
    {% endif %}
  

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>